In [7]:
import pandas as pd
import sqlalchemy
import pymysql
engine = sqlalchemy.create_engine('mysql+pymysql://root:C@paciti@localhost/rs3')
df = pd.read_sql_table('sprint 3 feb 2020', engine)
df

        Product   MyUnknownColumn Price   Size  Quantity
0        Chips:           Doritos   R15   150g       225
1                           Lays    R13   250g       400
2                           Simba   R13   250g       200
3   Cooldrinks:              Coke    R9  250ml       150
4                          Fanta     R9  250ml       120
5                         Sprite     R8  250ml       130
6   Chocolates:           Cadbury   R14   150g        55
7                            Tex   R13    150g        30
8                        Bar One    R15   150g        23
9         Pies:      Pepper Steak   R10               50
10                       Chicken    R10               55
11               Feta and Cheese    R13               25
12       Fruit:              Pear   R15    1kg        26
13                         Apple    R12  1.5kg        35
14                        Orange    R13    1kg        45
15    Cupcakes:          Vanilla   R3.5    50g        90
16                     Chocolate   R3.5    50g        89
17                    Red Velvet   R2.5    50g       100
18     Veggies:          Spinach     R5   250g        45
19                       Cabbage     R6   205g        65
20                      Brocolli     R4   300g        35

In [8]:

pk=df.to_csv('sprint3.csv',index=False)
dp=pd.read_csv("sprint3.csv")
dp

        Product   MyUnknownColumn Price   Size  Quantity
0        Chips:           Doritos   R15   150g       225
1           NaN             Lays    R13   250g       400
2           NaN             Simba   R13   250g       200
3   Cooldrinks:              Coke    R9  250ml       150
4           NaN            Fanta     R9  250ml       120
5           NaN           Sprite     R8  250ml       130
6   Chocolates:           Cadbury   R14   150g        55
7           NaN              Tex   R13    150g        30
8           NaN          Bar One    R15   150g        23
9         Pies:      Pepper Steak   R10    NaN        50
10          NaN          Chicken    R10    NaN        55
11          NaN  Feta and Cheese    R13    NaN        25
12       Fruit:              Pear   R15    1kg        26
13          NaN            Apple    R12  1.5kg        35
14          NaN           Orange    R13    1kg        45
15    Cupcakes:          Vanilla   R3.5    50g        90
16          NaN        Chocolate   R3.5    50g        89
17          NaN       Red Velvet   R2.5    50g       100
18     Veggies:          Spinach     R5   250g        45
19          NaN          Cabbage     R6   205g        65
20          NaN         Brocolli     R4   300g        35

In [11]:
import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  passwd="C@paciti",
  database="rs3"
)




cursor= mydb.cursor()

#cursor.execute("ALTER TABLE `sprint3` ADD `Product` VARCHAR(255) NOT NULL")

mydb.close()

In [15]:
import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  passwd="C@paciti",
  database="rs3"
)
mycursor = mydb.cursor()

sql = "UPDATE rs3.sprint3 SET Brands = 'Lacoste' WHERE chips = 'flyers'"

#mycursor.execute(sql)

mydb.commit()

print(mycursor.rowcount, "record(s) affected")

-1 record(s) affected

In [18]:

import sqlalchemy
import pymysql
engine = sqlalchemy.create_engine('mysql+pymysql://root:C@paciti@localhost/rs3')
df = pd.read_sql_table('sprint3', engine)
df

        Product   MyUnknownColumn Price   Size  Quantity
0        Chips:           Doritos   R15   150g       225
1                           Lays    R13   250g       400
2                           Simba   R13   250g       200
3   Cooldrinks:              Coke    R9  250ml       150
4                          Fanta     R9  250ml       120
5                         Sprite     R8  250ml       130
6   Chocolates:           Cadbury   R14   150g        55
7                            Tex   R13    150g        30
8                        Bar One    R15   150g        23
9         Pies:      Pepper Steak   R10               50
10                       Chicken    R10               55
11               Feta and Cheese    R13               25
12       Fruit:              Pear   R15    1kg        26
13                         Apple    R12  1.5kg        35
14                        Orange    R13    1kg        45
15    Cupcakes:          Vanilla   R3.5    50g        90
16                     Chocolate   R3.5    50g        89
17                    Red Velvet   R2.5    50g       100
18     Veggies:          Spinach     R5   250g        45
19                       Cabbage     R6   205g        65
20                      Brocolli     R4   300g        35

In [21]:

chips=pd.read_sql_query("Select Chips, `Price`, `Selling Price`,Quantity from rs3.sprint3", engine)
chips=chips.to_csv("sprint3.csv",index=False)
dp=pd.read_csv("sprint3.csv")
dp

InternalError: (pymysql.err.InternalError) (1054, "Unknown column 'Chips' in 'field list'")
[SQL: Select Chips, `Price`, `Selling Price`,Quantity from rs3.sprint3]
(Background on this error at: http://sqlalche.me/e/2j85)

In [23]:
drinks=pd.read_sql_query("Select Drinks, `Product_[0]`, `Selling Price_[0]`,`Quantity_[0]` from mydat.sprint", engine)
drinks=drinks.to_csv("sprint3.csv",index=False)
dp=pd.read_csv("sprint3.csv")
dp

InternalError: (pymysql.err.InternalError) (1049, "Unknown database 'mydat'")
[SQL: Select Drinks, `Product_[0]`, `Selling Price_[0]`,`Quantity_[0]` from mydat.sprint]
(Background on this error at: http://sqlalche.me/e/2j85)

In [28]:
import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  passwd="C@paciti",
  database="rs3"
)

mycursor = mydb.cursor()

sql = "INSERT INTO rs3.sprint3 (pies, Quantity) VALUES (%s, %s)"
val = ("Popcorns", "21")
#mycursor.execute(sql, val)

mydb.commit()

print(mycursor.rowcount, "record inserted.")

-1 record inserted.

In [31]:
mycursor = mydb.cursor()

sql = "UPDATE rs3.sprint3 SET `Selling Price` = 4, `Stock Price`=2 WHERE chips = 'Popcorns'"

#mycursor.execute(sql)

mydb.commit()

print(mycursor.rowcount, "record(s) affected")

-1 record(s) affected

In [33]:
mycursor = mydb.cursor()

sql = "INSERT INTO rs3.sprint3 (chips, Quantity) VALUES (%s, %s)"
val = ("Fritos", "501")
#mycursor.execute(sql, val)

mydb.commit()

print(mycursor.rowcount, "record inserted.")

-1 record inserted.

In [35]:

sql = "Delete from mydat.sprint1 where chips='fritos'"

#mycursor.execute(sql)

mydb.commit()

print(mycursor.rowcount, "record removed.")

-1 record removed.

In [41]:

cursor= mydb.cursor()

cursor.execute("ALTER TABLE rs3.sprint3 ADD `Expiry Date` Date NOT NULL")

mydb.close()

OperationalError: MySQL Connection not available.

In [44]:
import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  passwd="C@paciti",
  database="rs3"
)
mycursor = mydb.cursor()

sql = "UPDATE ra3.sprint3 SET Profit = `Selling Price`-`Stock Price`, Barcode=123456789, `expiry date`='2020-11-11' WHERE chips = 'simba'"

#mycursor.execute(sql)

mydb.commit()

print(mycursor.rowcount, "record(s) affected")

-1 record(s) affected